---
name: Daily Scripts
'on':
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
permissions:
  contents: write
  env: null
  chainstack_rpc: ${{secrets.CHAINSTACK}}
  alchemy_rpc: ${{secrets.ALCHEMY}}
  ankr_rpc: ${{secrets.ANKR}}
  quicknode_rpc: ${{secrets.QUICKNODE}}
  infura_rpc: ${{secrets.INFURA}}
  getblock_rpc: ${{secrets.GETBLOCK}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Python Packages
        id: cache-python
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}
        name: Install pip packages
        continue-on-error: true
        run: pip install -r ./requirements.txt
      - name: List pip packages
        run: echo "Cache Hit Status - ${{ steps.cache-python.outputs.cache-hit }}"; pip list packages
      - name: Run test
        run: |
          # Command to execute script 1
          python3 test.py
      
      
      - name: Commit report
        run: |
          git config --global user.name "nyssarex"
          git config --global user.email "amir.nyssambayev@gmail.com"
          git commit -am "Automated report"
          git push