---
name: Daily Scripts
'on':
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Python Packages
        id: cache-python
        uses: actions/cache@v4
        with:
          # pip cache files are stored in `~/.cache/pip`
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}
        name: Install pip packages
        continue-on-error: true
        run: pip install -r ./requirements.txt
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Script 1
        run: |
          # Command to execute script 1
          python3 pipeline.py

      - name: Run Script 2
        run: |
          # Command to execute script 2
          python3 html.py